#!/bin/bash

export PURRING_TRIBBLE_HOME=PURRING_TRIBBLE_HOME_VARIABLE
export PURRING_TRIBBLE_HOME_APPLICATION="$PURRING_TRIBBLE_HOME/application"
export PURRING_TRIBBLE_HOME_UI="$PURRING_TRIBBLE_HOME/ui"
export PURRING_TRIBBLE_HOME_TMP="$PURRING_TRIBBLE_HOME/tmp"
export PURRING_TRIBBLE_HOME_LOGS="$PURRING_TRIBBLE_HOME/logs"
export PURRING_TRIBBLE_DATABASE=$PURRING_TRIBBLE_HOME_APPLICATION/tribble.db
export PURRING_TRIBBLE_HOLIDAYS=$PURRING_TRIBBLE_HOME_APPLICATION/public_holidays.json

alias tribble="$PURRING_TRIBBLE_HOME/clock.sh m"
